# Generated by Django 4.1 on 2022-09-09 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=255, unique=True)),
                ('numero', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('non', models.CharField(max_length=100)),
                ('dat_anregistre', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'contact',
            },
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non', models.CharField(max_length=255)),
                ('modpas', models.CharField(max_length=255)),
                ('modpas2', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Itilizate',
                'verbose_name_plural': 'Itilizate yo',
            },
        ),
    ]
