# Generated by Django 4.1 on 2022-09-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='dat_anregistre',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='non',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, default='inconnu', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='relationship',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
